languageCode = "ja"
languageName = "日本語"
title = "tokap0 Website"

[params]
  displayName = "JA"
  isoCode = "ja"
  dateFormat = "2006年1月2日"
  # logo = "img/tokap0_icon.jpg"
  # secondaryLogo = "img/secondary-logo.png"
  # description = "My awesome website"
  # copyright = "Copy, _right?_ :thinking_face:"

[params.author]
  name = "tokap0"
  image = "img/tokap0_icon.jpg"
  headline = "ゲーム依存のセキュリティエンジニア"
  bio = "私について少し"
  links = [
     { github = "https://github.com/t0kapo" },
     { x-twitter = "https://x.com/tokap0" },
  ]